name: CI

on:
  push:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm

      - name: Build the app
        run: pnpm run build

      - name: Check formatting
        run: pnpm run format:check

      - name: Lint
        run: pnpm run lint:check

      - name: Unit tests
        run: pnpm run test
